# Made for: ${thisserver} with ${thisip}
version: "3"

networks:
    patroni:

services:
    etcd:
        image: quay.io/pflaeging/postgres-patroni-compose:v3.0.1
        restart: unless-stopped
        networks: [ patroni ]
        environment:
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_INITIAL_CLUSTER: ${server1}=http://${server1ip}:2380,${server2}=http://${server2ip}:2380,${server3}=http://${server3ip}:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: MyToken
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${thisip}:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://${thisip}:2379
            ETCD_DATA_DIR: /home/postgres/etcd-data
        volumes:
            - ./etcd-data:/home/postgres/etcd-data:Z
        container_name: patroni-etcd
        command: etcd -name ${thisserver}
        ports:
            - "2379:2379"
            - "2380:2380"
        extra_hosts:
            - "${server1}:${server1ip}"
            - "${server2}:${server2ip}"
            - "${server3}:${server3ip}"

    haproxy:
        image: quay.io/pflaeging/postgres-patroni-compose:v3.0.1
        restart: unless-stopped
        networks: [ patroni ]
        env_file: patroni.env
        hostname: haproxy
        container_name: patroni-haproxy
        ports:
            - "5000:5000"
            - "5001:5001"
            - "7000:7000"
        command: haproxy
        environment: &env
            ETCDCTL_ENDPOINTS: http://${server1ip}:2379,http://${server2ip}:2379,http://${server3ip}:2379
            PATRONI_ETCD3_HOSTS: "'${server1}:2379','${server2}:2379','${server3}:2379'"
            PATRONI_POSTGRESQL_DATA_DIR: /home/postgres/data
            PATRONI_SCOPE: patroni
        extra_hosts:
            - "${server1}:${server1ip}"
            - "${server2}:${server2ip}"
            - "${server3}:${server3ip}"

    patroni:
        image: quay.io/pflaeging/postgres-patroni-compose:v3.0.1
        restart: unless-stopped
        networks: [ patroni ]
        env_file: patroni.env
        hostname: postgres
        container_name: patroni-postgres
        environment: 
            <<: *env
            PATRONI_NAME: ${thisserver}
            PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${thisip}:5432
            PATRONI_RESTAPI_CONNECT_ADDRESS: ${thisip}:8008
            PATRONI_RESTAPI_LISTEN: "0.0.0.0:8008"
            PATRONI_POSTGRESQL_LISTEN: "0.0.0.0:5432"
        ports:
            - "5432:5432"
            - "8008:8008"
        volumes:
            - ./pg-data:/home/postgres/data:Z
        extra_hosts:
            - "${server1}:${server1ip}"
            - "${server2}:${server2ip}"
            - "${server3}:${server3ip}"
# End of config